{% set name = "holonote" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holonote-{{ version }}.tar.gz
  sha256: 20c0f8b6832629078565064d4d671ab8adcb18ba30b6a77d6ec10be11c0fccbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - holoviews >=1.18.0
    - pandas

test:
  imports:
    - holonote
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/holoviz/holonote
  summary: Annotate your data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Hoxbro
