{% set name = "holonote" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holonote-{{ version }}.tar.gz
  sha256: 3477f17d8d52b7e7d1244af2a80b02c006524af0063f686a4759734d83924be2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - holoviews >=1.18.0
    - pandas

test:
  imports:
    - holonote
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/holoviz/holonote
  summary: Annotate your data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Hoxbro
